# Parseable on Azure (Blob), distributed mode.
parseable:
  deploymentMode: distributed
  store:
    type: blob-store
    secretName: parseable-env-secret

  distributed:
    ingestor:
      replicas: 3
      persistence:
        staging:
          enabled: true
          storageClass: managed-csi
          size: 5Gi
    querier:
      persistence:
        hotTier:
          enabled: true
          storageClass: managed-csi
          size: 50Gi
